<div class="container home">

    <div class="bar__info py-3">
        <span><a href="/home"><i class="fa-solid fa-chevron-left"></i></a> Retour</span>
        <h1 class="title__h1">Details de la missions n° <?= $id ?> </h1>
        <p>Status : </p>

    </div>

    <div class="wrapper__grid">
        <div class="row  p-4 text-center">
            <div class="col-2 ">
                <p class="title__col" >Intitule :</p>
            </div>
            <div class="col-2">
                <p class="text__col">ex1</p>
            </div>
            <div class="col-2">
                <p class="title__col">Contact :</p>
            </div>
            <div class="col-2">
                <p class="text__col">Ex2</p>
            </div>
            <div class="col-2">
                <p class="title__col">Date Début :</p>
            </div>
            <div class="col-2">
                <p class="text__col">Ex3</p>
            </div>
        </div>

        <div class="row text-center p-4">
            <div class="col-2">
                <p class="title__col">Descriptif :</p>
            </div>
            <div class="col-2">
                <p class="text__col">ex1</p>
            </div>
            <div class="col-2">
                <p class="title__col">Contact par :</p>
            </div>
            <div class="col-2">
                <p class="text__col">Ex2</p>
            </div>
            <div class="col-2">
                <p class="title__col">Date fin :</p>
            </div>
            <div class="col-2">
                <p class="text__col">Ex3</p>
            </div>
        </div>

        <div class="row text-center p-4">
            <div class="col-2">
                <p class="title__col">Cible :</p>
            </div>
            <div class="col-2">
                <p class="text__col">ex1</p>
            </div>
            <div class="col-2">
                <p class="title__col">Spécialité Requise :</p>
            </div>
            <div class="col-2">
                <p class="text__col"></p>
            </div>

        </div>

        <div class="row text-center p-4">
            <div class="col-2">
                <p class="title__col">Pays :</p>
            </div>
            <div class="col-2">
                <p class="text__col">ex1</p>
            </div>
            <div class="col-2">
                <p class="title__col">Planque:</p>
            </div>
            <div class="col-2">
                <p class="text__col"></p>
            </div>
        </div>

      <div class="row p-4">
        <div class="col-2">
            <p class="title__col">Categories :</p>
        </div>
        <div class="col-2 ">
            <p class="text__col"></p>
        </div>
      </div>

    </div>



</div>