
<div class="container home">

    <h1 class="title__h1 mb-4" >Liste des Missions de l'Agence</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Intitulé</th>
                <th scope="col">Status</th>
                <th scope="col">Date Debut</th>
                <th scope="col">Date Fin</th>
                <th scope="col">Type Mission</th>
                <th scope="col">Consulté</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($missions as $mission): ?>
            <tr>
                <td><?= $mission['Id']?></td>
                <td><?= $mission['Title']?></td>
                <td><?= $mission['Status']?></td>
                <td><?= $mission['Date_debut']?></td>
                <td><?= $mission['Date_fin']?></td>
                <td><?= $mission['Type_mission']?></td>
                <td><a href="home/edit/<?=$mission['Id'] ?>">voir</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>

    </table>

</div>





