<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="website sur l'agence qui permet de voir l'ensemble des missions que nos faisons dans le monde avec nos agent spécialisé dans des disciplines diverses">
    <!-- CSS -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <title>Document</title>
</head>
<body>

    <header class="header">
       <p><a href="/">Secret Agency</a></p>
        <nav class="header__nav">         
                <li class="nav__link">
                   
                     <?php $login = isset($_SESSION['user']['name']) ? 'Deconnexion' : 'Connexion' ?>
                    <?php $url = isset($_SESSION['user']['name']) ? "/login/logout" : "/login" ?> 
                    <a href=<?= $url ?> >  <?= $login ?> </a></li> 
                
                   
              
                <li class="search-bar"> 
                    <input class="search-bar__input" name="search" type="text" placeholder="Search mission">
                    <button><i class="fa-solid fa-magnifying-glass"></i></button>
                </li>
          
        </nav>
    </header>

 
    <main>
        <?= $contenu ?>
    </main>
    
    <footer>
        <h3 class="text-center">Agence Secret </h3>
    </footer>

    <!-- JAVASCRIT -->
    <script src="/assets/js/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
</body>
</html>