

<div class="container form-wrapper">

    <div class="form-content p-4">

        <h1 class="title__h1 mb-4">Authentification requise !</h1>
           <!-- MESSAGE USER-->
     <?php  if (!empty($_SESSION['error'])): ?>
                    <p class="error"> <?=  $_SESSION['error']; unset($_SESSION['error']); ?></p>
     <?php endif; ?>
     
        <form action="login/authentification" method = "POST"> 
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="Enter email">
              
            </div>
            <div class="form-group my-3">
                <label for="password">Mot de passe</label>
                <input type="password" name="password" class="form-control" id="password" placeholder="Entrez mot de passe">
            </div>
            <div class="form-group ">
                <a href="#">Mot de passe oublié</a>
            </div>
            <input type="hidden" name="token" id="token" value="<?= $_SESSION['login_token'] ?>">
            <button type="submit" name="submit" class="btn-main my-3 p-2">SE CONNECTER</button>
        </form>

    </div>

</div>