

<div class="container main__block">

<div class="row main__wrapper">

    <div class="col-2 menu__side">
        <?php //include 'menu.phtml' ?>
        <?php include (dirname(__FILE__). '/../menu.phtml') ?>
    </div>

    <div class="col-8">

        <h2 class="title__h2 bar">Bienvue Administrateur : <span class="font--light"><?= $_SESSION['user']['name'] ?></span></h2>

        <div class="block__type row">
            <section class="col-12">
                
                <h3 class="text-center">Liste des Cibles</h3>
                <!-- MESSAGE USER-->
                <?php  if (!empty($_SESSION['success'])): ?>
            <p class="alert alert-success"> <?=  $_SESSION['success']; unset($_SESSION['success']); ?></p>
            <?php endif; ?>

                <button class="btn btn-info"><a href="/cible/create">AJOUTER CIBLE</a></button>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">CODE</th>
                            <th scope="col">NOM</th>
                            <th scope="col">PRENOM</th>
                            <th scope="col">DATE NAISSANCE</th>
                            <th scope="col">NATIONALITY</th>
                            <th scope="col">ACTION</th>
                          
                        </tr>
                    </thead>
                    <tbody>
                    
                    <?php foreach($cibles as $item): ?>
                        <tr>
                            <td><?= $item['Id']?></td>
                            <td><?= $item['Code']?></td>
                            <td><?= $item['Name']?></td>
                            <td><?= $item['Prenom']?></td>
                            <td><?= $item['Date_naissance']?></td>
                            <td><?= $item['Nationality']?></td>
                            <td>
                                <a href="/cible/edit/<?=$item['Id'] ?>" class ="btn btn-sm btn-info">voir</a>
                                <a href="/cible/delete/<?=$item['Id'] ?>" class ="btn btn-sm btn-danger">delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                        
                    </tbody>

                 </table>
            </section>
            
        </div>
    </div>
</div>
</div>
