
    <h2 class="title__h2 side_title text-center">Menu</h2>

    <ul class="side__menu">
    <li class="menu__item"><i class="fa-solid fa-table-columns"></i>
            <a href="\admin\">Dashboard</a></li>
        <li class="menu__item"><i class="fa-solid fa-user-secret"></i>
            <a href="\agents\">Agents</a></li>
        <li class="menu__item"><i class="fa-regular fa-id-badge"></i>
            <a href="#">Contact</a></li>
        <li class="menu__item"><i class="fa-solid fa-location-dot"></i>
            <a href="#">Planque</a></li>
        <li class="menu__item"><i class="fa-solid fa-bullseye"></i>
            <a href="#">Missions</a></li>
        <li class="menu__item"><i class="fa-solid fa-folder-closed"></i>
            <a href="#">Categories</a></li>
    </ul>
    
