
    <h2 class="title__h2 side_title text-center">Menu</h2>

    <ul class="side__menu">
    <li class="menu__item">  <a href="\admin\"><i class="fa-solid fa-table-columns"></i>
         <span class="menu__item-word"> Dashboard</span></a></li>
        <li class="menu__item"><a href="\agents\"><i class="fa-solid fa-user-secret"></i>
           <span class="menu__item-word"> Agents</span></a></li>
        <li class="menu__item"> <a href="\contact"><i class="fa-regular fa-id-badge"></i>
           <span class="menu__item-word">Contact</span></a></li>
        <li class="menu__item"> <a href="\planque"><i class="fa-solid fa-location-dot"></i>
          <span class="menu__item-word"> Planque</span></a></li>
        <li class="menu__item"> <a href="\cible"><i class="fa-solid fa-bullseye"></i>
          <span class="menu__item-word"> Cible</span></a></li>
        <li class="menu__item">  <a href="\mission"><i class="fa-sharp fa-solid fa-users-viewfinder"></i>
         <span class="menu__item-word"> Missions</span></a></li>
       
    </ul>
    
