

<div class="container main__block">

<div class="row main__wrapper">

    <div class="col-2 menu__side">

        <?php //include 'menu.phtml'; ?>
        <?php include (dirname(__FILE__). '/../menu.phtml') ?>
    </div>

    <div class="col-8">

        <h2 class="title__h2 bar">Bienvue Administrateur : <span class="font--light"><?= $_SESSION['user']['name'] ?></span></h2>

        <div class="block__type row screen">
            <article class="col-12 ">
                <h3 class="text-center">Créer un nouvel contact</h3>            
            </article>
            <form action="/contact/create" method="POST" class="form__block">
                <div class="form-group">
                    <label for="name">Nom</label>
                    <input type="text" id="name" name="name">
                </div>
                <div class="form-group">
                    <label for="prenom">prenom</label>
                    <input type="text" id="prenom" name="prenom">
                </div>
                <div class="form-group">
                    <label for="naissance">Date de Naissance</label>
                    <input type="text" id="naissance" name="naissance">
                </div>
              
            
                <div class="form-group">
                    <label for="nationalite">nationalite</label>
                    <input type="text" id="nationalite" name="nationalite">
                </div>
                <div class="form-group">
                    <label for="code">code</label>
                    <input type="text" id="code" name="code">
                </div>

                <button name="submit" class="btn btn-secondary">CREER</button>
            </form>
            
        </div>
    </div>
</div>
</div>