

<div class="container main__block">

<div class="row main__wrapper">

    <div class="col-2 menu__side">

        <?php //include 'menu.phtml'; ?>
        <?php include (dirname(__FILE__). '/../menu.phtml') ?>
    </div>

    <div class="col-8">

        <h2 class="title__h2 bar">Bienvue Administrateur : <span class="font--light"><?= $_SESSION['user']['name'] ?></span></h2>

        <div class="block__type row screen">
            <article class="col-12 ">
                <h3 class="text-center">Fiche de la Mission</h3>            
            </article>
            <form action="/mission/edit/<?= $mission['Id'] ?>" method="POST" class="form__block">
                <div class="form-group">
                    <label for="title">Titre</label>
                    <input type="text" id="title" name="Title" value="<?= $mission['Title'] ?>">
                </div>
                <div class="form-group">
                    <label for="Description">Description</label>
                    <input type="text" id="Description" name="Description" value="<?= $mission['Description'] ?>">
                </div>
                <div class="form-group">
                    <label for="Status">Status</label>
                    <input type="text" id="Status" name="Status" value="<?= $mission['Status'] ?>">
                </div>
                <div class="form-group">
                    <label for="date_debut">Date Debut </label>
                    <input type="text" id="date_debut" name="date_debut" value="<?= $mission['Date_debut'] ?>">
                </div>
                <div class="form-group">
                    <label for="date_fin">Date Fin </label>
                    <input type="text" id="date_fin" name="date_fin" value="<?= $mission['Date_fin'] ?>">
                </div>
                <div class="form-group">
                    <label for="Type_mission">Type Mission</label>
                    <input type="text" id="Type_mission" name="Type_mission" value="<?= $mission['Type_mission'] ?>">
                </div>
                <div class="form-group">
                    <label for="Code_name">Nom Code</label>
                    <input type="text" id="Code_name" name="Code_name" value="<?= $mission['Code_name'] ?>">
                </div>
                <div class="form-group">
                    <label for="Agent">Agent</label>
                    <select name="Agent" id="Agent">
                        <option value="<?= $mission['Agent_Id']?>"> <?= $Agent_Name ?>   </option>
                        <?php foreach($agents as $item) : ?>
                           <option value="<?= $item['Id']?>"><?= $item['Name'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="Cible">Cible</label>
                    <select name="Cible" id="Cible">
                    <option value="<?= $mission['Cible_Id']?>"> <?= $cible_Name ?> </option>
                             <?php foreach($cibles as $item) : ?>
                           <option value="<?= $item['Id']?>"><?= $item['Name'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="Planque">Planque</label>
                    <select name="Planque" id="Planque">
                    <option value="<?= $mission['Planque_Id']?>"> <?= $Planque_Adress ?> </option>
                        <?php foreach($planques as $item) : ?>
                           <option value="<?= $item['Id']?>"> Adress : <?= $item['Adress'] ?>  <?= $item['Country']?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="Contact">Contact</label>
                    <select name="Contact" id="Contact">
                       <option value="<?= $mission['Contact_Id']?>"> <?= $Contact_Name ?> </option>
                        <?php foreach($contacts as $item) : ?>
                           <option value="<?= $item['Id']?>"><?= $item['Name'] ?> <?= $item['Prenom']?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <button name="submit" class="btn btn-secondary">MODIFIER</button>
            </form>
            
        </div>
    </div>
</div>
</div>