

<div class="container main__block">

<div class="row main__wrapper">

    <div class="col-2 menu__side">

        <?php //include 'menu.phtml'; ?>
        <?php include (dirname(__FILE__). '/../menu.phtml') ?>
    </div>

    <div class="col-8">

        <h2 class="title__h2 bar">Bienvue Administrateur : <span class="font--light"><?= $_SESSION['user']['name'] ?></span></h2>

        <div class="block__type row screen">
            <article class="col-12 ">
                <h3 class="text-center">Créer une nouvelle planque</h3>            
            </article>
            <form action="/planque/create" method="POST" class="form__block">
                <div class="form-group">
                    <label for="adress">Adress</label>
                    <input type="text" id="adress" name="adress">
                </div>
                <div class="form-group">
                    <label for="country">Country</label>
                    <input type="text" id="country" name="country">
                </div>
                <div class="form-group">
                    <label for="code">Code</label>
                    <input type="text" id="code" name="code">
                </div>
              
            
                <div class="form-group">
                    <label for="type">Type</label>
                    <input type="text" id="type" name="type">
                </div>
              

                <button name="submit" class="btn btn-secondary">CREER</button>
            </form>
            
        </div>
    </div>
</div>
</div>