

<div class="container main__block">

<div class="row main__wrapper">

    <div class="col-2 menu__side">
        <?php //include 'menu.phtml' ?>
        <?php include (dirname(__FILE__). '/../menu.phtml') ?>
    </div>

    <div class="col-8">

        <h2 class="title__h2 bar">Bienvue Administrateur : <span class="font--light"><?= $_SESSION['user']['name'] ?></span></h2>

        <div class="block__type row">
            <section class="col-12">
                
                <h3 class="text-center">Liste des Planques</h3>
                <!-- MESSAGE USER-->
                <?php  if (!empty($_SESSION['success'])): ?>
            <p class="alert alert-success"> <?=  $_SESSION['success']; unset($_SESSION['success']); ?></p>
            <?php endif; ?>

                <button class="btn btn-info"><a href="/planque/create">AJOUTER PLANQUE</a></button>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">ADRESS</th>
                            <th scope="col">COUNTRY</th>
                            <th scope="col">CODE</th>
                            <th scope="col">TYPE</th>
                            <th scope="col">ACTION</th>
                          
                        </tr>
                    </thead>
                    <tbody>
                    
                    <?php foreach($planque as $item): ?>
                        <tr>
                            <td><?= $item['Id']?></td>
                            <td><?= $item['Adress']?></td>
                            <td><?= $item['Country']?></td>
                            <td><?= $item['Code']?></td>
                            <td><?= $item['Type']?></td>
                            <td>
                                <a href="/planque/edit/<?=$item['Id'] ?>" class ="btn btn-info">voir</a>
                                <a href="/planque/delete/<?=$item['Id'] ?>" class ="btn btn-danger">delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                        
                    </tbody>

                 </table>
            </section>
            
        </div>
    </div>
</div>
</div>